@extends('layout.app')
@section('title',$record->exists?'Edit company or plant':'Create company or plant')
@section('content')
@php
$errorKeys=array_keys($errors->toArray());
$startStep=collect($errorKeys)->contains(fn($key)=>str_starts_with($key,'contacts.'))?1:(collect($errorKeys)->contains(fn($key)=>str_starts_with($key,'addresses.'))?2:0);
@endphp
<form class="card corporate-record-form company-wizard-form user-corporate-form w-full p-4 sm:p-6 {{ $record->exists?'is-editing':'' }}" method="POST" action="{{ $record->exists?route('admin.companies.update',$record):route('admin.companies.store') }}" data-company-wizard data-start-step="{{ $startStep }}">
    @csrf @if($record->exists) @method('PUT') @endif
    <div class="mb-7 rounded-xl border border-slate-200 bg-slate-50 p-4">
        <div class="mb-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div class="h-full rounded-full bg-cyan-600 transition-all duration-300" data-wizard-progress style="width:25%"></div></div>
        <ol class="grid grid-cols-4 gap-2">
            @foreach([['Company','Basic details'],['Contact','Communication'],['Address','Location'],['Review','Confirm & save']] as $index=>$item)
            <li><button class="group w-full rounded-lg border border-transparent px-2 py-2 text-left transition" type="button" data-step-button="{{ $index }}"><span class="flex items-center gap-2"><span class="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-slate-300 bg-white text-xs font-bold" data-step-circle>{{ $index+1 }}</span><span><b class="block text-sm">{{ $item[0] }}</b><small class="hidden text-xs font-normal text-slate-500 sm:block">{{ $item[1] }}</small></span></span></button></li>
            @endforeach
        </ol>
    </div>
    @if($errors->any())<div class="form-error-alert" role="alert"><span class="form-error-alert-icon">!</span><div><strong>Unable to save</strong><p>Please correct the highlighted fields.</p></div></div>@endif

    <section data-step-panel="0">
        <p class="text-xs font-bold uppercase tracking-[.16em] text-cyan-700">Step 1 of 4</p><h3 class="mb-1 text-xl font-semibold">Company or plant details</h3><p class="mb-5 text-sm text-slate-500">Enter the organization identity, hierarchy and tax information.</p>
        <div class="corporate-form-grid">
            <div class="form-field"><label class="label">Code *</label><input class="input" name="company_code" value="{{ old('company_code',$record->company_code) }}" required>@error('company_code')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div class="form-field"><label class="label">Company / Plant name *</label><input class="input" name="company_name" value="{{ old('company_name',$record->company_name) }}" required>@error('company_name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div class="form-field"><label class="label">Record type *</label><select class="input" name="record_type" required><option value="">— Select —</option><option value="1" @selected((string)old('record_type',$record->record_type)==='1')>Company</option><option value="2" @selected((string)old('record_type',$record->record_type)==='2')>Plant</option></select></div>
            <div class="form-field"><label class="label">Parent company</label><select class="input" name="parent_company_id"><option value="">— None —</option>@foreach($options['parent_company_id'] as $item)<option value="{{ $item->company_code }}" @selected((string)old('parent_company_id',$record->parent_company_id)===(string)$item->company_code)>{{ $item->company_code }} - {{ $item->company_name }}</option>@endforeach</select></div>
            <div class="form-field"><label class="label">GSTIN</label><input class="input" name="gstin" value="{{ old('gstin',$record->gstin) }}"></div>
            <div class="form-field"><label class="label">PAN</label><input class="input" name="pan" value="{{ old('pan',$record->pan) }}"></div>
            <div class="form-field"><label class="label">Status *</label><select class="input" name="Status" required><option value="1" @selected((string)old('Status',$record->exists?$record->Status:1)==='1')>Active</option><option value="0" @selected((string)old('Status',$record->exists?$record->Status:1)==='0')>Inactive</option></select></div>
        </div>
    </section>

    <section data-step-panel="1" class="hidden">
        <p class="text-xs font-bold uppercase tracking-[.16em] text-cyan-700">Step 2 of 4</p><h3 class="text-xl font-semibold">Contact details</h3><p class="mb-5 text-sm text-slate-500">Connect an existing contact or create a primary communication record.</p>
        <div class="space-y-3" data-contact-rows>
            @foreach($formContacts as $index=>$contact)
            <div class="repeatable-row rounded-lg border border-slate-200 p-3" data-repeatable-row><div class="corporate-form-grid repeatable-form-grid">
                @if(!empty($contact['id']))<input type="hidden" name="contacts[{{ $index }}][id]" value="{{ $contact['id'] }}">@endif
                <div class="form-field"><label class="label">Contact type</label><select class="input" name="contacts[{{ $index }}][type]"><option value="1" @selected((string)($contact['type']??'1')==='1')>Mobile</option><option value="2" @selected((string)($contact['type']??'')==='2')>Telephone</option><option value="3" @selected((string)($contact['type']??'')==='3')>Email</option><option value="4" @selected((string)($contact['type']??'')==='4')>Emergency contact</option></select></div>
                <div class="form-field"><label class="label">Contact value</label><input class="input" name="contacts[{{ $index }}][value]" value="{{ $contact['value']??'' }}">@error("contacts.$index.value")<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div class="form-field"><input type="hidden" name="contacts[{{ $index }}][is_primary]" value="0"><label class="flex gap-2"><input type="checkbox" name="contacts[{{ $index }}][is_primary]" value="1" @checked($contact['is_primary']??false)> Primary contact</label></div>
            </div><button class="btn-secondary mt-2 hidden" type="button" data-remove-row>Remove</button></div>
            @endforeach
        </div>
        <button class="btn-secondary mt-3" type="button" data-add-contact>＋ Add another contact</button>
    </section>

    <section data-step-panel="2" class="hidden">
        <p class="text-xs font-bold uppercase tracking-[.16em] text-cyan-700">Step 3 of 4</p><h3 class="text-xl font-semibold">Address details</h3><p class="mb-5 text-sm text-slate-500">Choose an existing location or create a complete new address.</p>
        <div class="space-y-3" data-address-rows>
            @foreach($formAddresses as $index=>$address)
            <div class="repeatable-row rounded-lg border border-slate-200 p-3" data-repeatable-row><div class="corporate-form-grid repeatable-form-grid">
                @if(!empty($address['id']))<input type="hidden" name="addresses[{{ $index }}][id]" value="{{ $address['id'] }}">@endif
                <div class="form-field"><label class="label">Address type</label><select class="input" name="addresses[{{ $index }}][type]"><option value="1" @selected((string)($address['type']??'1')==='1')>Current</option><option value="2" @selected((string)($address['type']??'')==='2')>Permanent</option><option value="3" @selected((string)($address['type']??'')==='3')>Office</option><option value="4" @selected((string)($address['type']??'')==='4')>Plant</option><option value="5" @selected((string)($address['type']??'')==='5')>Subsidiary</option></select></div>
                @foreach(['line_1'=>'Address line 1','line_2'=>'Address line 2'] as $name=>$label)
                <div class="form-field"><label class="label">{{ $label }}</label><input class="input" name="addresses[{{ $index }}][{{ $name }}]" value="{{ $address[$name]??'' }}">@error("addresses.$index.$name")<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                @endforeach
                @foreach(['state'=>'State','district'=>'District','city'=>'City','postal_code'=>'Postal code'] as $name=>$label)
                <div class="form-field"><label class="label">{{ $label }}</label><select class="input" name="addresses[{{ $index }}][{{ $name }}]" data-india-{{ str_replace('_','-',$name) }} data-selected="{{ $address[$name]??'' }}"><option value="{{ $address[$name]??'' }}">{{ $address[$name]?:('Select '.strtolower($label)) }}</option></select>@error("addresses.$index.$name")<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                @endforeach
                <input type="hidden" name="addresses[{{ $index }}][country]" value="India" data-name="country">
            </div><button class="btn-secondary mt-2 hidden" type="button" data-remove-row>Remove</button></div>
            @endforeach
        </div>
        <button class="btn-secondary mt-3" type="button" data-add-address>＋ Add another address</button>
    </section>

    <section data-step-panel="3" class="hidden">
        <p class="text-xs font-bold uppercase tracking-[.16em] text-cyan-700">Step 4 of 4</p><h3 class="mb-1 text-xl font-semibold">Review and save</h3><p class="mb-5 text-sm text-slate-500">Confirm the information below before creating the record.</p>
        <div class="rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7" data-company-review>Review the entered company, contact and address information, then save.</div>
    </section>

    <div class="mt-6 flex gap-3 border-t border-slate-100 pt-5">
        <button class="btn-secondary" type="button" data-wizard-previous>Cancel</button><div class="flex-1"></div>
        <button class="btn-primary" type="button" data-wizard-next>Next →</button>
        <button class="btn-primary hidden" type="submit" data-wizard-submit>{{ $record->exists?'Update':'Create' }} company / plant</button>
    </div>
</form>
@endsection
@push('scripts')
<script>
window.mountCompanyForms=()=>{
 const form=document.querySelector('[data-company-wizard]:not([data-company-wizard-ready])');if(!form)return;
 form.dataset.companyWizardReady='true';
 const contactTemplate=`<div class="repeatable-row rounded-lg border border-slate-200 p-3" data-repeatable-row><div class="corporate-form-grid repeatable-form-grid"><div class="form-field"><label class="label">Contact type</label><select class="input" data-name="type"><option value="1">Mobile</option><option value="2">Telephone</option><option value="3">Email</option><option value="4">Emergency contact</option></select></div><div class="form-field"><label class="label">Contact value</label><input class="input" data-name="value"></div><div class="form-field"><input type="hidden" data-name="is_primary" value="0"><label class="flex gap-2"><input type="checkbox" data-name="is_primary" value="1"> Primary contact</label></div></div><button class="btn-secondary mt-2" type="button" data-remove-row>Remove</button></div>`;
 const locationSelect=(name,label)=>`<div class="form-field"><label class="label">${label}</label><select class="input" data-name="${name}" data-india-${name.replace('_','-')}><option value="">Select ${label.toLowerCase()}</option></select></div>`;
 const addressTemplate=`<div class="repeatable-row rounded-lg border border-slate-200 p-3" data-repeatable-row><div class="corporate-form-grid repeatable-form-grid"><div class="form-field"><label class="label">Address type</label><select class="input" data-name="type"><option value="1">Current</option><option value="2">Permanent</option><option value="3">Office</option><option value="4">Plant</option><option value="5">Subsidiary</option></select></div>${[['line_1','Address line 1'],['line_2','Address line 2']].map(([name,label])=>`<div class="form-field"><label class="label">${label}</label><input class="input" data-name="${name}"></div>`).join('')}${locationSelect('state','State')}${locationSelect('district','District')}${locationSelect('city','City')}${locationSelect('postal_code','Postal code')}<input type="hidden" data-name="country" value="India"></div><button class="btn-secondary mt-2" type="button" data-remove-row>Remove</button></div>`;
 const renumber=(container,prefix)=>{[...container.querySelectorAll('[data-repeatable-row]')].forEach((row,index)=>row.querySelectorAll('[data-name], [name]').forEach(field=>{const key=field.dataset.name||field.name.match(/\[([^\]]+)\]$/)?.[1];if(key)field.name=`${prefix}[${index}][${key}]`;}));container.querySelectorAll('[data-remove-row]').forEach(button=>button.classList.toggle('hidden',container.querySelectorAll('[data-repeatable-row]').length===1));};
 const setupRepeater=(container,prefix,button,template)=>{renumber(container,prefix);button.addEventListener('click',()=>{container.insertAdjacentHTML('beforeend',template);renumber(container,prefix)});container.addEventListener('click',event=>{if(!event.target.closest('[data-remove-row]'))return;event.target.closest('[data-repeatable-row]').remove();renumber(container,prefix)});};
 setupRepeater(form.querySelector('[data-contact-rows]'),'contacts',form.querySelector('[data-add-contact]'),contactTemplate);setupRepeater(form.querySelector('[data-address-rows]'),'addresses',form.querySelector('[data-add-address]'),addressTemplate);
 const endpoints={states:@json(route('admin.india-locations.states')),districts:@json(route('admin.india-locations.districts')),cities:@json(route('admin.india-locations.cities')),postal:@json(route('admin.india-locations.postal-codes'))};
 const enhance=field=>{if(field._searchable)return;field.classList.add('hidden');const combo=document.createElement('div');combo.className='relative';combo.innerHTML='<input class="input pr-9" autocomplete="off" role="combobox" aria-autocomplete="list"><button class="absolute inset-y-0 right-0 px-3 text-slate-500" type="button" tabindex="-1" aria-label="Show options">▾</button><div class="absolute z-50 mt-1 hidden max-h-56 w-full overflow-auto rounded-lg border border-slate-200 bg-white py-1 shadow-lg" role="listbox"></div>';field.before(combo);const input=combo.querySelector('input'),toggle=combo.querySelector('button'),menu=combo.querySelector('[role="listbox"]');let values=[];const close=()=>{menu.classList.add('hidden');input.setAttribute('aria-expanded','false')};const render=()=>{const query=input.value.trim().toLocaleLowerCase(),matches=(query?values.filter(value=>String(value).toLocaleLowerCase().includes(query)):values).slice(0,150);menu.replaceChildren();if(!matches.length){const empty=document.createElement('p');empty.className='px-3 py-2 text-sm text-slate-500';empty.textContent='No matching options';menu.append(empty)}else matches.forEach(value=>{const option=document.createElement('button');option.type='button';option.className='block w-full px-3 py-2 text-left text-sm hover:bg-cyan-50';option.textContent=value;option.addEventListener('mousedown',event=>{event.preventDefault();field.value=value;input.value=value;close();field.dispatchEvent(new Event('change',{bubbles:true}))});menu.append(option)});menu.classList.remove('hidden');input.setAttribute('aria-expanded','true')};input.addEventListener('focus',render);input.addEventListener('input',()=>{field.value='';render();field.dispatchEvent(new Event('change',{bubbles:true}))});input.addEventListener('blur',()=>setTimeout(close,100));toggle.addEventListener('mousedown',event=>event.preventDefault());toggle.addEventListener('click',()=>menu.classList.contains('hidden')?render():close());field._searchable={refresh:(next,selected='')=>{values=next;input.value=selected;input.placeholder=`Search ${labelFor(field)}`;input.disabled=field.disabled;toggle.disabled=field.disabled},disable:()=>{input.value='';input.placeholder=`Select ${labelFor(field)} first`;input.disabled=true;toggle.disabled=true;close()}};};
 const escapeHtml=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
 const labelFor=field=>field.matches('[data-india-postal-code]')?'postal code':field.dataset.indiaCity!==undefined?'city':field.dataset.indiaDistrict!==undefined?'district':'state';
 const reset=field=>{field.innerHTML=`<option value="">Select ${labelFor(field)}</option>`;field.value='';field.disabled=true;field._searchable?.disable()};
 const fill=async(field,url,selected='')=>{field.disabled=true;field._searchable?.disable();field.innerHTML=`<option value="">Loading ${labelFor(field)}...</option>`;try{const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Unable to load locations');const values=await response.json();field.innerHTML=`<option value="">Select ${labelFor(field)}</option>${values.map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join('')}`;if(selected&&!values.includes(selected))field.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(selected)}">${escapeHtml(selected)}</option>`);field.value=selected||'';field.disabled=false;field._searchable?.refresh(values,selected)}catch(error){field.innerHTML=`<option value="">Unable to load ${labelFor(field)}</option>`;field.disabled=false;field._searchable?.refresh([],'')}};
 const initIndiaRow=async row=>{if(!row||row.dataset.indiaReady)return;row.dataset.indiaReady='1';const state=row.querySelector('[data-india-state]'),district=row.querySelector('[data-india-district]'),city=row.querySelector('[data-india-city]'),postal=row.querySelector('[data-india-postal-code]');if(!state)return;[state,district,city,postal].forEach(enhance);const selected={state:state.dataset.selected||state.value,district:district.dataset.selected||district.value,city:city.dataset.selected||city.value,postal:postal.dataset.selected||postal.value};reset(district);reset(city);reset(postal);await fill(state,endpoints.states,selected.state);if(selected.state)await fill(district,`${endpoints.districts}?state=${encodeURIComponent(selected.state)}`,selected.district);if(selected.state&&selected.district)await fill(city,`${endpoints.cities}?state=${encodeURIComponent(selected.state)}&district=${encodeURIComponent(selected.district)}`,selected.city);if(selected.state&&selected.district&&selected.city)await fill(postal,`${endpoints.postal}?state=${encodeURIComponent(selected.state)}&district=${encodeURIComponent(selected.district)}&city=${encodeURIComponent(selected.city)}`,selected.postal);state.addEventListener('change',async()=>{reset(district);reset(city);reset(postal);if(state.value)await fill(district,`${endpoints.districts}?state=${encodeURIComponent(state.value)}`)});district.addEventListener('change',async()=>{reset(city);reset(postal);if(district.value)await fill(city,`${endpoints.cities}?state=${encodeURIComponent(state.value)}&district=${encodeURIComponent(district.value)}`)});city.addEventListener('change',async()=>{reset(postal);if(city.value)await fill(postal,`${endpoints.postal}?state=${encodeURIComponent(state.value)}&district=${encodeURIComponent(district.value)}&city=${encodeURIComponent(city.value)}`)});};
 const addressRows=form.querySelector('[data-address-rows]');addressRows.querySelectorAll('[data-repeatable-row]').forEach(initIndiaRow);new MutationObserver(records=>records.flatMap(record=>[...record.addedNodes]).filter(node=>node.nodeType===1).forEach(node=>initIndiaRow(node.matches('[data-repeatable-row]')?node:node.querySelector('[data-repeatable-row]')))).observe(addressRows,{childList:true});
 const panels=[...form.querySelectorAll('[data-step-panel]')],buttons=[...form.querySelectorAll('[data-step-button]')],next=form.querySelector('[data-wizard-next]'),previous=form.querySelector('[data-wizard-previous]'),submit=form.querySelector('[data-wizard-submit]'),progress=form.querySelector('[data-wizard-progress]');let step=Number(form.dataset.startStep||0);
 const show=value=>{step=Math.max(0,Math.min(3,value));panels.forEach((panel,index)=>panel.classList.toggle('hidden',index!==step));buttons.forEach((button,index)=>{const circle=button.querySelector('[data-step-circle]'),active=index===step,done=index<step;button.classList.toggle('border-cyan-200',active);button.classList.toggle('bg-cyan-50',active);button.classList.toggle('text-cyan-800',active);button.classList.toggle('text-emerald-700',done);circle.classList.toggle('border-cyan-600',active);circle.classList.toggle('bg-cyan-600',active);circle.classList.toggle('text-white',active||done);circle.classList.toggle('border-emerald-600',done);circle.classList.toggle('bg-emerald-600',done);circle.textContent=done?'✓':index+1;});progress.style.width=`${(step+1)*25}%`;next.classList.toggle('hidden',step===3);submit.classList.toggle('hidden',step!==3);previous.textContent=step?'← Previous':'Cancel';if(step===3){const get=name=>form.elements[name]?.value||'Not provided',type=get('record_type')==='2'?'Plant':'Company',contactCount=[...form.querySelectorAll('[name$="[value]"]')].filter(field=>field.value.trim()).length,addressCount=[...form.querySelectorAll('[name$="[line_1]"]')].filter(field=>field.value.trim()).length;form.querySelector('[data-company-review]').innerHTML=`<div class="grid gap-3 sm:grid-cols-2"><p><span class="text-slate-500">Code</span><br><strong>${get('company_code')}</strong></p><p><span class="text-slate-500">Name</span><br><strong>${get('company_name')}</strong></p><p><span class="text-slate-500">Record type</span><br><strong>${type}</strong></p><p><span class="text-slate-500">Contacts</span><br><strong>${contactCount}</strong></p><p><span class="text-slate-500">Addresses</span><br><strong>${addressCount}</strong></p></div>`;}};
 next.addEventListener('click',()=>{const invalid=[...panels[step].querySelectorAll('input,select,textarea')].find(field=>!field.checkValidity());if(invalid){invalid.reportValidity();return}show(step+1)});previous.addEventListener('click',()=>step?show(step-1):window.parent.document.querySelector('[data-global-form-close]')?.click());buttons.forEach(button=>button.addEventListener('click',()=>{const target=Number(button.dataset.stepButton);if(target<=step)show(target)}));show(step);
};
window.mountCompanyForms();
</script>
@endpush
