<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('tbl_addresses',function(Blueprint $t){$t->id();$t->enum('address_type',['1','2','3','4','5'])->default('1')->comment('1=Current, 2=Permanent, 3=Office, 4=Plant, 5=Subsidiaries');$t->string('address_line_1');$t->string('address_line_2')->nullable();$t->string('city',100);$t->string('district',100)->nullable();$t->string('state',100);$t->string('postal_code',20);$t->string('country',100)->default('India');$t->enum('status',['0','1'])->default('1');$this->audit($t);});
Schema::create('tbl_contacts',function(Blueprint $t){$t->id();$t->enum('contact_type',['1','2','3','4'])->comment('1=Mobile, 2=Telephone, 3=Email, 4=Emergency contact');$t->string('contact_value');$t->boolean('is_primary')->default(true);$t->enum('status',['0','1'])->default('1');$this->audit($t);});
Schema::create('tbl_login',function(Blueprint $t){$t->id();$t->string('username',100)->unique();$t->string('password');$t->string('token')->nullable();$t->boolean('status')->default(true);$t->unsignedBigInteger('created_by')->nullable()->index();$t->timestamp('created_at')->nullable()->useCurrent();$t->unsignedBigInteger('updated_by')->nullable()->index();$t->timestamp('updated_at')->nullable()->useCurrent()->useCurrentOnUpdate();});
Schema::create('tbl_usertypes',function(Blueprint $t){$t->id();$t->string('type_code',30)->unique();$t->string('type_name',100);$t->string('description')->nullable();$t->enum('status',['0','1'])->default('1');$this->audit($t);});
Schema::create('tbl_users',function(Blueprint $t){$t->id();$t->string('reference_id',50);$t->foreignId('user_type_code')->constrained('tbl_usertypes')->restrictOnDelete();$t->unique(['user_type_code','reference_id'],'uq_user_type_reference');$t->string('first_name',100);$t->string('last_name',100);$t->enum('gender',['1','2','3','4'])->nullable();$t->integer('is_verified');$t->date('date_of_birth')->nullable();$t->enum('marital_status',['1','2','3','4'])->nullable();$t->date('anniversary_date')->nullable();$t->foreignId('contact_id')->nullable()->constrained('tbl_contacts')->nullOnDelete();$t->foreignId('address_id')->nullable()->constrained('tbl_addresses')->nullOnDelete();$t->unsignedBigInteger('education_id')->nullable()->index();$t->unsignedBigInteger('photo_id')->nullable()->index()->comment('No photo table was supplied');$t->foreignId('login_id')->nullable()->unique()->constrained('tbl_login')->nullOnDelete();$t->enum('status',['0','1'])->default('1');$this->audit($t);});
Schema::create('tbl_education',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained('tbl_users')->cascadeOnDelete();$t->string('education_level',100);$t->string('degree_name',150);$t->string('institution_name');$t->string('university_name')->nullable();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->boolean('is_current')->default(false);$t->string('grade',50)->nullable();$t->string('image_path',500)->nullable();$t->timestamp('uploaded_at')->nullable();$t->enum('status',['pending','verified','rejected','inactive'])->default('pending');$this->audit($t);});
Schema::table('tbl_users',fn(Blueprint $t)=>$t->foreign('education_id')->references('id')->on('tbl_education')->nullOnDelete());}
private function audit(Blueprint $t):void{$t->timestamp('created_at')->useCurrent();$t->unsignedBigInteger('created_by')->nullable()->index();$t->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();$t->unsignedBigInteger('updated_by')->nullable()->index();}
public function down():void{Schema::table('tbl_users',fn(Blueprint $t)=>$t->dropForeign(['education_id']));foreach(['tbl_education','tbl_users','tbl_usertypes','tbl_login','tbl_contacts','tbl_addresses'] as $table)Schema::dropIfExists($table);}};
